env:  
  node: true  
extends:  
  - plugin:@typescript-eslint/recommended  
  - prettier
  - plugin:prettier/recommended  
parser: '@typescript-eslint/parser'  
parserOptions:  
  ecmaVersion: 9  
  project: 
    - './tsconfig.json'
    - './dist/index.js'
plugins:  
  - '@typescript-eslint'
ignorePatterns:
  - 'dist/*.js'